<a href="https://colab.research.google.com/github/anurg/aicourse/blob/main/Numpy_labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Learning Numpy
import numpy as np
print(np.__version__)
x = [1,2,3,4,5,6,7,8]
z=np.array(x)
print(z,type(z))
print(z.shape)
print(z.dtype)
print(z+10)
print(z-1)
print(z*10)
#floats
f= [1.2,3.1,4.12,5.345]
y=np.array(f)
print(y,type(y),y.shape,y.dtype)
#nested list -- elements need to have same length (homogeneous)
n=[[1,2,3,4],[5,6,7,8]]
z=np.array(n)
print(z,type(z),z.shape,z.dtype)

#6) 3 dimensional array
d = np.array([
    [[1, 2,3],
     [4, 5, 6]],
    [[7, 8,9],
    [10, 11, 12]]
        ])
print(d*2)
print(d.shape)

2.0.2
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
(8,)
int64
[11 12 13 14 15 16 17 18]
[0 1 2 3 4 5 6 7]
[10 20 30 40 50 60 70 80]
[1.2   3.1   4.12  5.345] <class 'numpy.ndarray'> (4,) float64
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4) int64
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
(2, 2, 3)


In [24]:
#7)np.zeros
#  np.ones
#we can create a matrix full of zeroes or ones using np.zeros and np.one commands.
#It can be used when you initialized the weights during the first iteration in
#TensorFlow and other statistic tasks.
# syntax :np.zeros(shape, dtype=float)

print(np.zeros((3,3),dtype=int))
print(np.ones((3,3),dtype=int))
print(np.ones((1,2,3),dtype=int))

#8)reshape():in some occasions, you need to reshape the data from wide to long
#syntax:  np.reshape(a, newShape)
#a: Array that you want to reshape
e= np.array([[1,2,3],[4,5,6]])
print(e,e.shape)
print(e.reshape(3,2))
print(e.reshape(1,6))
print(e.reshape(6,1))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]]]
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
#9)flatten():flattening the array,When you deal with some neural network like,we need to
#flatten the array
import numpy as np
e= np.array([[1,2,3],[4,5,6]])
s=e.reshape(6,1)
print(s)
print(s.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [32]:
#hstack & vstack
f=np.array([1,2,3])
g=np.array([4,5,6])
h=np.array([7,8,9])
print(np.hstack([f,g,h])) #horizontal stack
print(np.vstack([f,g,h])) #vertical stack

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#NumPy - Array From Numerical Ranges
import numpy as np
#14) arange() :generating range of values
#syntax:   numpy.arange(start, stop,step)
print(np.arange(11))
print(np.arange(5,dtype=float))
x = np.arange(1,20,2)
print(x,type(x))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0. 1. 2. 3. 4.]
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [45]:
#15)numpy.linspace
#This function is similar to arange() function.
#here instead of step size, the number of evenly spaced values between the interval is specified.
#syntax:
#numpy.linspace(start, stop, num)
import numpy as np
print(np.linspace(0,20,5,dtype=int))
# print(np.linspace(10,100)) # default is 50 values

[ 0  5 10 15 20]


In [54]:
#16)NumPy - Indexing & Slicing
a = np.arange(20)
s= slice(2,20,2)
print(a)
print(s)
print(a[s])

a = np.arange(5,25)
s= slice(2,20,2)
print(a[s])
#or
a=np.arange(20)
print(a[2:20:2])

print(a[5])
print(a[:5])
print(a[15:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
slice(2, 20, 2)
[ 2  4  6  8 10 12 14 16 18]
[ 7  9 11 13 15 17 19 21 23]
[ 2  4  6  8 10 12 14 16 18]
5
[0 1 2 3 4]
[15 16 17 18 19]


In [63]:
#V) slicing on multi-dimensional ndarray
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print(a[1:][0][0])
print('The items in the second column are:')
print(a[...,1])
print(a[...,1:])
# Now we will slice all items from the second row
print(a[1,...])
print(a[1:,...])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
3
The items in the second column are:
[2 4 5]
[[2 3]
 [4 5]
 [5 6]]
[3 4 5]
[[3 4 5]
 [4 5 6]]


In [68]:
#17)NumPy - Iterating Over Array

#NumPy package contains an iterator object numpy.nditer. It is an efficient
#multidimensional iterator object using which it is possible to iterate over
#an array.creating a 3X4 array using arange() function and iterate over it using nditer.
a = np.arange(0,60,5)
a = a.reshape(6,2)
print(a)
for p in np.nditer(a):
  print(p)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [72]:
#18) Transpose : here rows becomes columns
a= np.arange(0,60,5)
a=a.reshape(4,3)
print(a)
print(a.T)  # transpose the matrix
# for p in np.nditer(a.T):
#   print(p)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]
[[ 0 15 30 45]
 [ 5 20 35 50]
 [10 25 40 55]]


In [78]:
#20.Array Manipulation
#i)split: Splits an array into multiple sub-arrays
import numpy as np
a = np.arange(9)
print(np.split(a,3))
print(np.split(a,[2,5]))

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8])]


In [86]:
import numpy as np

x = np.arange(9.0) # [0., 1., 2., 3., 4., 5., 6., 7., 8.]
# Split before index 2, and before index 6
result_indices = np.split(x, [2, 6])
print(result_indices)
# Output: [array([0., 1.]), array([2., 3., 4., 5.]), array([6., 7., 8.])]

[array([0., 1.]), array([2., 3., 4., 5.]), array([6., 7., 8.])]


In [87]:
a=np.arange(16).reshape(4,4)
print(a)
print(np.hsplit(a,2))
print(np.vsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [88]:
#Finding dimensions of a array
#ndim:This can be used to find the dimensions of the array.

import numpy as np
arr = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [9, 10, 11, 23]])
print(np.ndim(arr))

2


In [89]:
#sum(),max(),min()
a = np.array([1,2,3,10,15,4])
print("max",a.max())
print("min",a.min())
print("sum",a.sum())

max 15
min 1
sum 35


In [95]:
#arithmetic operations are performed on the two multi-dimensional arrays a and b.
import numpy as np
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12, 19, 29]])
print("a + b",a+b)
print("a - b",a-b)
print("a * b",a*b)
print("a / b",a/b)

a + b [[ 2  4 33]
 [22 34 33]]
a - b [[  0   0  27]
 [ -2  -4 -25]]
a * b [[  1   4  90]
 [120 285 116]]
a / b [[ 1.          1.         10.        ]
 [ 0.83333333  0.78947368  0.13793103]]


In [102]:
#NumPy Functions

#1)numpy.sum(): This function is used to compute the sum of all elements,
#the sum of each row and the sum of each column of a given array.
import numpy as np
a=np.array([0.5,0.3])
print(np.sum(a))

a=np.array([0.4,0.5,0.9,6.1])
print(np.sum(a,dtype=np.int32))

a=np.array([[1,4],[3,5]])
print(np.sum(a))
print(a.sum(axis=0)) #ex:4 column sum
print(a.sum(axis=1)) #ex:5  row sum

0.8
6
13
[4 9]
[5 8]
