<a href="https://colab.research.google.com/github/anurg/aicourse/blob/main/Numpy_labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# Learning Numpy
import numpy as np
print(np.__version__)
list1=[1,2,3,4,5]
array = np.array(list1)
print(array)
print(array+10)
print(array-1)
print(array*2)
print(array.shape)
print(array.dtype)

list1=[[1,2,3,4,5],[6,7,8,9,10]]
array = np.array(list1)
print(array)
print(array+10)
print(array-1)
print(array*2)
print(array.shape)
print(array.dtype)

2.0.2
[1 2 3 4 5]
[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
(5,)
int64
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
(2, 5)
int64
