<a href="https://colab.research.google.com/github/anurg/aicourse/blob/main/Numpy_labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Learning Numpy
import numpy as np
print(np.__version__)
x = [1,2,3,4,5,6,7,8]
z=np.array(x)
print(z,type(z))
print(z.shape)
print(z.dtype)
print(z+10)
print(z-1)
print(z*10)
#floats
f= [1.2,3.1,4.12,5.345]
y=np.array(f)
print(y,type(y),y.shape,y.dtype)
#nested list -- elements need to have same length (homogeneous)
n=[[1,2,3,4],[5,6,7,8]]
z=np.array(n)
print(z,type(z),z.shape,z.dtype)

#6) 3 dimensional array
d = np.array([
    [[1, 2,3],
     [4, 5, 6]],
    [[7, 8,9],
    [10, 11, 12]]
        ])
print(d*2)
print(d.shape)

2.0.2
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
(8,)
int64
[11 12 13 14 15 16 17 18]
[0 1 2 3 4 5 6 7]
[10 20 30 40 50 60 70 80]
[1.2   3.1   4.12  5.345] <class 'numpy.ndarray'> (4,) float64
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4) int64
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
(2, 2, 3)


In [24]:
#7)np.zeros
#  np.ones
#we can create a matrix full of zeroes or ones using np.zeros and np.one commands.
#It can be used when you initialized the weights during the first iteration in
#TensorFlow and other statistic tasks.
# syntax :np.zeros(shape, dtype=float)

print(np.zeros((3,3),dtype=int))
print(np.ones((3,3),dtype=int))
print(np.ones((1,2,3),dtype=int))

#8)reshape():in some occasions, you need to reshape the data from wide to long
#syntax:  np.reshape(a, newShape)
#a: Array that you want to reshape
e= np.array([[1,2,3],[4,5,6]])
print(e,e.shape)
print(e.reshape(3,2))
print(e.reshape(1,6))
print(e.reshape(6,1))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]]]
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
#9)flatten():flattening the array,When you deal with some neural network like,we need to
#flatten the array
import numpy as np
e= np.array([[1,2,3],[4,5,6]])
s=e.reshape(6,1)
print(s)
print(s.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]


In [32]:
#hstack & vstack
f=np.array([1,2,3])
g=np.array([4,5,6])
h=np.array([7,8,9])
print(np.hstack([f,g,h])) #horizontal stack
print(np.vstack([f,g,h])) #vertical stack

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
#NumPy - Array From Numerical Ranges
import numpy as np
#14) arange() :generating range of values
#syntax:   numpy.arange(start, stop,step)
print(np.arange(11))
print(np.arange(5,dtype=float))
x = np.arange(1,20,2)
print(x,type(x))

[ 0  1  2  3  4  5  6  7  8  9 10]
[0. 1. 2. 3. 4.]
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [44]:
#15)numpy.linspace
#This function is similar to arange() function.
#here instead of step size, the number of evenly spaced values between the interval is specified.
#syntax:
#numpy.linspace(start, stop, num)
import numpy as np
print(np.linspace(0,20,5,dtype=int))
# print(np.linspace(10,100)) # default is 50 values

[ 0  5 10 15 20]
[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]
