<a href="https://colab.research.google.com/github/anurg/aicourse/blob/main/Numpy_labs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# Learning Numpy
import numpy as np
print(np.__version__)
x = [1,2,3,4,5,6,7,8]
z=np.array(x)
print(z,type(z))
print(z.shape)
print(z.dtype)
print(z+10)
print(z-1)
print(z*10)
#floats
f= [1.2,3.1,4.12,5.345]
y=np.array(f)
print(y,type(y),y.shape,y.dtype)
#nested list -- elements need to have same length (homogeneous)
n=[[1,2,3,4],[5,6,7,8]]
z=np.array(n)
print(z,type(z),z.shape,z.dtype)

#6) 3 dimensional array
d = np.array([
    [[1, 2,3],
     [4, 5, 6]],
    [[7, 8,9],
    [10, 11, 12]]
        ])
print(d*2)
print(d.shape)

2.0.2
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
(8,)
int64
[11 12 13 14 15 16 17 18]
[0 1 2 3 4 5 6 7]
[10 20 30 40 50 60 70 80]
[1.2   3.1   4.12  5.345] <class 'numpy.ndarray'> (4,) float64
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> (2, 4) int64
[[[ 2  4  6]
  [ 8 10 12]]

 [[14 16 18]
  [20 22 24]]]
(2, 2, 3)


In [24]:
#7)np.zeros
#  np.ones
#we can create a matrix full of zeroes or ones using np.zeros and np.one commands.
#It can be used when you initialized the weights during the first iteration in
#TensorFlow and other statistic tasks.
# syntax :np.zeros(shape, dtype=float)

print(np.zeros((3,3),dtype=int))
print(np.ones((3,3),dtype=int))
print(np.ones((1,2,3),dtype=int))

#8)reshape():in some occasions, you need to reshape the data from wide to long
#syntax:  np.reshape(a, newShape)
#a: Array that you want to reshape
e= np.array([[1,2,3],[4,5,6]])
print(e,e.shape)
print(e.reshape(3,2))
print(e.reshape(1,6))
print(e.reshape(6,1))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[[1 1 1]
  [1 1 1]]]
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [26]:
#9)flatten():flattening the array,When you deal with some neural network like,we need to
#flatten the array
s=e.reshape(6,1)
print(s)
print(s.flatten())

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
